services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      PGUSER: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    image: wcs_project-server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    build: ./server
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - ./server:/app

  client:
    image: wcs_project-client
    restart: always
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app