services:
  db:
    restart: always
    image: mongo
    environment:
      DB_PASSWORD: password
      DB_USER: user1
    ports:
      - "6000:6000"
    healthcheck:
      test:  ["CMD", "docker-healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 10

  back:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: localhost
    build: ./back
    ports:
      - 4000:4000
      - 4001:4001
    volumes:
      - ./back/src:/app/src